export const RECORD_USERINFO = 'RECORD_USERINFO';
export const RECORD_ADDRESS = 'RECORD_ADDRESS';
export const RECORD_SHOPINFO = 'RECORD_SHOPINFO';
export const ADD_CART = 'ADD_CART';
export const QUIT_LOGIN = 'QUIT_LOGIN';
export const CLEAR_SHOPINFO = 'CLEAR_SHOPINFO';

